/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author ANGIE
 */
public class Moto extends javax.swing.JPanel {

    /**
     * Creates new form Carro
     */
    public Moto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtFld_buscarCarro = new javax.swing.JTextField();
        Bttn_buscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(690, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(650, 570));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 580, -1));
        add(TxtFld_buscarCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 320, 30));

        Bttn_buscar.setText("Buscar");
        add(Bttn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 140, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bttn_buscar;
    private javax.swing.JTextField TxtFld_buscarCarro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
